# Workflow name
name: Reploy

# cron job scheduled for every 24 hours 
on:
  schedule:
  - cron:  '0 */24 * * *'
    
jobs:
  # This workflow contains a single job called "build"
  reploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      # Call Vercel hook
      - name: Trigger reploy
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/QmTKpSzRwz7WovkmrroLqTKJmAQ75W17dQU3q3h4EqKqJd/czT97Wmd6D
